import type { MarketingDiagnostic } from "@/types/marketing-strategy";

// Representative diagnostic used by the /diagnostic preview page.
// Spans all 5 severity bands, includes the 4 strategy-tier problems,
// and 3 "insufficient data" problems (honesty: discovery can't judge them).
export const SAMPLE_DIAGNOSTIC: MarketingDiagnostic = {
  maturityScore: 42,
  strengths: ["Strong founder network", "Early product-market signal"],
  weaknesses: ["No defined ICP", "No measurement in place"],
  opportunities: ["Underserved niche", "Content gap vs. competitors"],
  threats: ["Well-funded incumbent", "Commoditized category"],
  summary: "Solid product instinct, but the go-to-market is undefined and unmeasured.",
  criticalProblems: ["undefined_audience", "standard_positioning"],
  problems: [
    {
      key: "undefined_audience",
      label: "The target audience is not properly defined",
      severity: "critical",
      isStrategic: true,
      evidence: "0 audience segments defined, no primary ICP.",
      recommendation: "Define and prioritize a primary ICP with real trigger moments.",
      confidence: "high",
      dataSufficiency: "measured",
    },
    {
      key: "standard_positioning",
      label: "Positioning is too standard, no differentiation",
      severity: "deep",
      isStrategic: true,
      evidence: "Differentiator reads like the category norm.",
      recommendation: "Articulate a sharper, contrarian differentiator vs. competitors.",
      confidence: "medium",
      dataSufficiency: "inferred",
    },
    {
      key: "painless_problem",
      label: "The problem solved is not painful enough",
      severity: "problematic",
      isStrategic: true,
      evidence: 'Pain level reported as "bloquant".',
      recommendation: "Re-anchor on a more acute, urgent pain or higher-stakes use case.",
      confidence: "high",
      dataSufficiency: "measured",
    },
    {
      key: "weak_product",
      label: "The product is not good enough",
      severity: "normal",
      isStrategic: true,
      evidence: "Insufficient data — product quality is not captured by discovery.",
      recommendation: "Gather product feedback (NPS, churn reasons, win/loss).",
      confidence: "low",
      dataSufficiency: "insufficient",
    },
    {
      key: "poor_measurement",
      label: "Performance measurement is not pertinent",
      severity: "deep",
      isStrategic: false,
      evidence: "No primary-goal metric, unit-economics knowledge: none.",
      recommendation: "Define measurable goals and instrument KPIs (CAC, conversion).",
      confidence: "high",
      dataSufficiency: "measured",
    },
    {
      key: "guesswork",
      label: "Too many assumptions and guesswork",
      severity: "problematic",
      isStrategic: false,
      evidence: "Unit-economics knowledge: none, 1 hypothesis noted.",
      recommendation: "Replace assumptions with tracked metrics and testable hypotheses.",
      confidence: "medium",
      dataSufficiency: "measured",
    },
    {
      key: "outdated_tactics",
      label: "Using outdated marketing tactics",
      severity: "problematic",
      isStrategic: false,
      evidence: "1 active channel, 2 abandoned, 2 inactive tools.",
      recommendation: "Audit current tactics; retire inactive tools, refresh channels.",
      confidence: "low",
      dataSufficiency: "inferred",
    },
    {
      key: "insufficient_content",
      label: "Not enough marketing content",
      severity: "deep",
      isStrategic: false,
      evidence: "1 active channel, 0 organic/content channels.",
      recommendation: "Build a consistent content engine on the best-performing channel.",
      confidence: "low",
      dataSufficiency: "inferred",
    },
    {
      key: "rough_sales",
      label: "Sales process is not smooth",
      severity: "problematic",
      isStrategic: false,
      evidence: "Qualified revenue pipeline tracked: false.",
      recommendation: "Define a clear lead→deal pipeline with a marketing→sales handoff.",
      confidence: "low",
      dataSufficiency: "inferred",
    },
    {
      key: "wrong_talents",
      label: "Not the right talents in the team",
      severity: "normal",
      isStrategic: false,
      evidence: "Team size 2, 2 skills, 1 gap, dedicated=true.",
      recommendation: "Close the identified skill gap via training or outsourcing.",
      confidence: "high",
      dataSufficiency: "measured",
    },
    {
      key: "unclear_messaging",
      label: "Messaging is unclear or not appealing",
      severity: "normal",
      isStrategic: false,
      evidence: "Transformation articulated, 0 proof points.",
      recommendation: "Sharpen the before→after transformation and add proof points.",
      confidence: "medium",
      dataSufficiency: "measured",
    },
    {
      key: "imperfect_pricing",
      label: "Pricing is not perfect",
      severity: "normal",
      isStrategic: false,
      evidence: "Unit-economics knowledge: basic (LTV/CAC unknown).",
      recommendation: "Measure LTV/CAC and payback before tuning pricing.",
      confidence: "low",
      dataSufficiency: "inferred",
    },
    {
      key: "inconsistent_efforts",
      label: "No consistency and patience in efforts",
      severity: "normal",
      isStrategic: false,
      evidence: "1 channel tried and abandoned.",
      recommendation: "Commit to fewer channels with a sustained cadence.",
      confidence: "low",
      dataSufficiency: "inferred",
    },
    {
      key: "poor_systems",
      label: "Systems and processes are not good",
      severity: "easily_fixed",
      isStrategic: false,
      evidence: "2 tools: 2 well-configured, 0 inactive.",
      recommendation: "Document processes and keep the stack lean.",
      confidence: "medium",
      dataSufficiency: "measured",
    },
    {
      key: "bad_creative",
      label: "Creative work (copy and design) is bad",
      severity: "normal",
      isStrategic: false,
      evidence: "Insufficient data — creative quality is not captured by discovery.",
      recommendation: "Review recent copy/design samples against best-in-class references.",
      confidence: "low",
      dataSufficiency: "insufficient",
    },
    {
      key: "no_innovation",
      label: "No innovation and stuck in the past",
      severity: "normal",
      isStrategic: false,
      evidence: "Insufficient data — innovation posture is not captured by discovery.",
      recommendation: "Allocate a recurring experiment budget for new channels and formats.",
      confidence: "low",
      dataSufficiency: "insufficient",
    },
  ],
};
